apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: client
          image: dockerquark/journal-api-prod
          ports:
            - containerPort: 4000
          env:
            - name: TYPEORM_ENTITIES
              value: src/entities/*.*
            - name: TYPEORM_MIGRATIONS
              value: src/migrations/*.*
            - name: TYPEORM_MIGRATIONS_DIR
              value: src/migrations
            - name: REDISHOST
              value: redis-cluster-ip
            - name: REDISPORT
              value: "6379"
            - name: TYPEORM_CONNECTION
              value: postgres
            - name: TYPEORM_USERNAME
              value: postgres
            - name: TYPEORM_HOST
              value: 127.0.0.1
            - name: TYPEORM_SYNCHRONIZE
              value: "false"
            - name: TYPEORM_LOGGING
              value: "false"
            - name: TYPEORM_DATABASE
              value: postgres
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: PGPASSWORD
            - name: TYPEORM_PORT
              value: "5432"
            - name: SALT
              value: "10"
            - name: ACCESS_TOKEN_EXPIRY
              value: 10m
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_EXPIRY
              value: 30d
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: REFRESH_TOKEN_SECRET
            - name: SELF_URL
              value: https://journal-typescript.app
            - name: SYNC
              value: "false"
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.14
          command:
            [
              "/cloud_sql_proxy",
              "-instances=journal-typescript:europe-west1:journal-typescript-database=tcp:5432",
              "-credential_file=/secrets/cloudsql/credentials.json",
            ]
          securityContext:
            runAsUser: 2 # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
