version: "3"
services:
  db:
    image: postgres:latest
    volumes:
      - ./api/pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - REDISHOST=redis
      - REDISPORT=6379
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - SALT=1
    ports:
      - 4000:4000
