version: "3"
services:
  postgres:
    image: postgres:latest
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - PGUSER="postgres"
      - PGHOST="postgres"
      - PGDATABASE="postgres"
      - PGPASSWORD="postgres_password"
      - PGPOR=5432
