version: "3"
services:
  db:
    image: postgres:latest
    volumes:
      - ./api/pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - PGUSER="postgres"
      - PGHOST="postgres"
      - PGDATABASE="postgres"
      - PGPASSWORD="postgres_password"
      - PGPOR=5432
