version: "3"
services:
  db:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - ./api/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      - api
      - web
    ports:
      - "3050:80"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./web:/app
    environment:
      - USE_STAGING=false
      - LOCAL_URL=http://192.168.0.106:3050
      - STAGING_URL=https://journal-typescript.app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - TYPEORM_ENTITIES=src/entities/*.*
      - TYPEORM_MIGRATIONS=src/migrations/*.*
      - TYPEORM_MIGRATIONS_DIR=src/migrations
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=db
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=postgres_password
      - TYPEORM_DATABASE=postgres
      - TYPEORM_PORT=5432
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_LOGGING=true
      - REDISHOST=redis
      - REDISPORT=6379
      - SALT=1
      - ACCESS_TOKEN_SECRET=secret
      - ACCESS_TOKEN_EXPIRY=10d
      - REFRESH_TOKEN_SECRET=secret
      - REFRESH_TOKEN_EXPIRY=10d
      - SELF_URL=http://localhost:3050
      - SYNC=true
