apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: client
          image: dockerquark/journal-api-prod
          ports:
            - containerPort: 4000
          env:
            - name: REDISHOST
              value: redis-cluster-ip
            - name: REDISPORT
              value: "6379"
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: ps-cluster-ip
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: PGPASSWORD
            - name: PGPORT
              value: "5432"
            - name: SALT
              value: "10"
            - name: ACCESS_TOKEN_EXPIRY
              value: 10m
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_EXPIRY
              value: 30d
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: REFRESH_TOKEN_SECRET
            - name: SELF_URL
              value: http://192.168.64.4
            - name: SYNC
              value: "true"
