apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: client
          image: dockerquark/journal-api-prod
          ports:
            - containerPort: 4000
          env:
            - name: REDISHOST
              value: redis-cluster-ip
            - name: REDISPORT
              value: "6379"
            - name: TYPEORM_CONNECTION
              value: postgres
            - name: TYPEORM_USERNAME
              value: postgres
            - name: TYPEORM_HOST
              value: ps-cluster-ip
            - name: TYPEORM_SYNCHRONIZE
              value: "true"
            - name: TYPEORM_LOGGING
              value: "true"
            - name: TYPEORM_DATABASE
              value: postgres
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: PGPASSWORD
            - name: TYPEORM_PORT
              value: "5432"
            - name: SALT
              value: "10"
            - name: ACCESS_TOKEN_EXPIRY
              value: 10m
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_EXPIRY
              value: 30d
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: REFRESH_TOKEN_SECRET
            - name: SELF_URL
              value: http://192.168.64.4
